questions=['Which one is a type of sorting algorithm in Python?',
           'What will this code output ? \n print("Hello\\nWorld!")',
           'Who discovered Python ?',
           'Command to print something in Python ?',
           'Odd one out ?',
           'Which is not a Python module ?',
           'Keyword for declaring global scope variable ?',
           'Not a data type in Python ?',
           'Which is the extension of Python file ?',
           'Code to reverse a string ?',
           'What is the maximum possible length of an identifier?',
           'Which of the following is an invalid variable?',
           'Which is the correct operator for power(x,y)?',
           'Which one of these is floor division?',
           'What is the answer to this expression, 22 % 3 is?',
           'Which one of the following has the highest precedence in the expression?',
           'Which of the following will run without errors?',
           'What will be the output of the following Python code? \n str="Hello" \n str[:2]',
           'What data type is below object? \n L = [1, 23, "hello", 1]',
           'What is the result of cmp(3, 1)?',
           'What is the result of round(0.5) – round(-0.5)?',
           'What will be the output if  x=456 \n print("%-06d"%x)',
         ]

choice_answers=[['Bubble', 'Linear', 'Dynamic', 'Two-Dimensional'],
                ['Hello\\nWorld!','Hello\nWorld!','Error','No Output'],
                ['Guido van Russom','Bill Gates','Elon Musk','Charles Babbage'],
                ['cout<<','console.log()','print()','System.out.print()'],
                ['for','while','if','do-while'],
                ['TKinter','Math','string','hello'],
                ['main','global','while','variable'],
                ['str','float','int','text'],
                ['.cpp','.htm','.py','.apk'],
                ['str[::-1]','str.reverse()','str[-1]','str.reverse(True)'],
                ['31 characters','63 characters','79 characters','None'],
                ['my_string_1','1st_string','foo','_'],
                ['x^y','x**y','x^^y','None'],
                ['/','//','%','None'],
                ['7','0','1','5'],
                ['Exponential','Addition','Multiplication','Parentheses'],
                ['round(45.8)','round(6352.898,2,5)','round()','round(7463.123,2,1)'],
                ['he','lo','olleh','hello'],
                ['List','Dictionary','Array','Tuple'],
                ['1','0','True','False'],
                ['1.0','2.0','0.0','None'],
                ['000456','456000','456','Error'],
                
        ]

answers=[0,1,0,2,2,3,1,3,2,0,3,1,1,1,2,3,0,0,0,0,1,2]
